#!/usr/bin/env bash
# Install nginx on web server; Nginx should be listening on port 80

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo ufw allow "Nginx HTTP"
sudo chown -R $USER:$USER /var/www/html/index.html
sudo echo "Hello World!" > /var/www/html/index.html
sudo -i '/listen 80 default_server;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2=TGUlwu4 permanent;' /etc/nginx/sites-available/dwfault
sudo service nginx restart
