#!/usr/bin/env bash
# changing home IP with hosts file
cp /etc/hosts ~/hosts.new
sed -i "s/.*localhost$/127.0.0.2	localhost/g" ~/hosts.new
sed -i "s/.*google.com//g" ~/hosts.new
echo "8.8.8.8	google.com" >> ~/hosts.new
cat ~/hosts.new > /etc/hosts
